Srini\Bundle\JobeetBundle\Entity\Category:
  type: entity
  table: jobcategory
  fields:
    id:
        type: integer
        id: true
        generator:
            strategy: AUTO
    name:
      type: string
      length: 255
      unique: true
  oneToMany:
    jobs:
      targetEntity: Job
      mappedBy: category
    category_affiliates:
      targetEntity: CategoryAffiliate
      mappedBy: category