Srini\Bundle\JobeetBundle\Entity\Job:
  properties:
    category:
      - NotBlank: ~
    company:
      - NotBlank: ~
    position:
      - NotBlank: ~
    location:
      - NotBlank: ~
    description:
      - NotBlank: ~
    how_to_apply:
      - NotBlank: ~
    file:
      - Image: ~
    token:
      - NotBlank: ~
    type:
      - NotBlank: ~
      - Choice: {callback: [Srini\Bundle\JobeetBundle\Utils\Jobeet, getTypesValues]}
    email:
      - NotBlank: ~
      - Email: ~