parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 45720a93da5c591884f015417588f039aa615694
    database_path: null
    mailer_transport: smtp
    mailer_host : smtp.gmail.com
    mailer_user: ilythica
    mailer_password: !lYthic@
    mailer_encryption: ssl
    mailer_auth_mode: login