<?php

namespace Srini\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepositoyCLass
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepositoyCLass extends EntityRepository
{
}