job:
    pattern:  /
    defaults: { _controller: "SriniJobeetBundle:Job:index" }

job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "SriniJobeetBundle:Job:show" }
    requirements:
        id:  \d+

job_new:
    pattern:  /new
    defaults: { _controller: "SriniJobeetBundle:Job:new" }

job_create:
    pattern:  /create
    defaults: { _controller: "SriniJobeetBundle:Job:create" }
    requirements: { _method: post }

job_edit:
    pattern:  /{token}/edit
    defaults: { _controller: "SriniJobeetBundle:Job:edit" }

job_update:
    pattern:  /{token}/update
    defaults: { _controller: "SriniJobeetBundle:Job:update" }
    requirements: { _method: post }

job_delete:
    pattern:  /{token}/delete
    defaults: { _controller: "SriniJobeetBundle:Job:delete" }
    requirements: { _method: post }

job_preview:
    pattern:  /{company}/{location}/{token}/{position}
    defaults: { _controller: "SriniJobeetBundle:Job:preview" }
    requirements:
        token:  \w+

job_publish:
    pattern:  /{token}/publish
    defaults: { _controller: "SriniJobeetBundle:Job:publish" }
    requirements: { _method: post}
    
job_extend:
    pattern:  /{token}/extend
    defaults: { _controller: "SriniJobeetBundle:Job:extend" }
    requirements: { _method: post }