job:
    pattern:  /
    defaults: { _controller: "SriniJobeetBundle:Job:index" }

job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "SriniJobeetBundle:Job:show" }
    requirements:
        id:  \d+

job_new:
    pattern:  /new
    defaults: { _controller: "SriniJobeetBundle:Job:new" }

job_create:
    pattern:  /create
    defaults: { _controller: "SriniJobeetBundle:Job:create" }
    requirements: { _method: post }

job_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SriniJobeetBundle:Job:edit" }

job_update:
    pattern:  /{id}/update
    defaults: { _controller: "SriniJobeetBundle:Job:update" }
    requirements: { _method: post }

job_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SriniJobeetBundle:Job:delete" }
    requirements: { _method: post }
