SriniTaskBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SriniTaskBundle:Default:index }
    
SriniTaskBundle_tasknew:
    pattern:  /task/new
    defaults: { _controller: SriniTaskBundle:Default:new }
    
task_success:
    pattern: /task/success
    defaults: {_controller: SriniTaskBundle:Default:show}