srini_front_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SriniFrontBundle:Default:index , name: Srinivasan}
    
srini_front_blog:
    pattern:  /blog
    defaults: { _controller: SriniFrontBundle:Default:blog }
    
_contact:
    pattern:  /contact
    defaults: { _controller: SriniFrontBundle:Default:contact}

_welcome:
    pattern:  /
    defaults: { _controller: SriniFrontBundle:Default:index , name: Srinivasan}
    
srini_front_about:
    pattern:  /about
    defaults: { _controller: SriniFrontBundle:Default:about }

front_blog_show:
    prefix: /blog
    pattern:  /{id}/{slug}
    defaults: { _controller: "SriniFrontBundle:Default:show" }
    requirements:
        _method:  GET
        id: \d+