parameters:
#    srini_front.example.class: Srini\Bundle\FrontBundle\Example

services:
#    srini_front.example:
#        class: %srini_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
