_welcome:
    pattern:  /
    defaults: { _controller: SriniBlogBundle:Default:index,first_name:Srinivasan,last_name:Kumar,color:red }
      
SriniBlogBundle_homepage:
    pattern:  /hello/{first_name}/{last_name}/{color}
    defaults: { _controller: SriniBlogBundle:Default:index, color:green, last_name:""}
      


SriniBlogBundle_welcome:
    pattern:  /welcome/{slug}
    defaults: { _controller: SriniBlogBundle:Default:welcome}
