Srini\Bundle\BlogBundle\Entity\Blog:
    type: entity
    table: blog
    repositoryClass: Srini\Bundle\BlogBundle\Entity\BlogRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: 255
        blog:
            type: text
        published:
            type: boolean
        author:
          type: string
          length: 255
        slug:
          type: string
          length: 128
          gedmo:
            slug:
              separator: _
              style: camel
              fields:
                - title
          
        created_at:
          type: datetime
          gedmo:
              timestampable:
                 on: create
        updated_at:
          type: datetime
          gedmo:
            timestampable:
              on: update
    manyToOne:
          category:
            targetEntity: Category
            cascade: {  }
            mappedBy: null
            inversedBy: blogs
            joinColumns:
              category:
                referencedColumnName: id
            orphanRemoval: false
    oneToMany:
      comments:
        targetEntity: Comment
        cascade: {  }
        mappedBy: blog
        orphanRemoval: false
    lifecycleCallbacks: {  }
