Srini\Bundle\BlogBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: Srini\Bundle\BlogBundle\Entity\CommentRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
        comment:
            type: text
        created_at:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated_at:
            type: datetime
            gedmo:
              timestampable:
                on: update
    manyToOne:
      blog:
        targetEntity: Blog
        cascade: {  }
        mappedBy: null
        inversedBy: comments
        joinColumns:
          blog_id:
            referencedColumnName: id
        orphanRemoval: false
    lifecycleCallbacks: {  }
